require("dotenv").config();
const express=require("express"),{Pool}=require("pg"),multer=require("multer"),bcrypt=require("bcryptjs"),jwt=require("jsonwebtoken"),xlsx=require("xlsx"),fs=require("fs");
const path=require("path");
const app=express(), pool=new Pool({connectionString:process.env.DATABASE_URL});
const upload=multer({dest:process.env.UPLOAD_DIR||"./uploads"});
app.use(express.json({limit:"4mb"})); app.use(express.urlencoded({extended:true})); app.use(express.static("public"));
function auth(req,res,next){const h=req.headers.authorization||"";try{req.user=jwt.verify(h.replace("Bearer ",""),process.env.JWT_SECRET);next()}catch{res.status(401).json({error:"auth_required"})}}
app.get("/api/health",async(req,res)=>{try{await pool.query("select 1");res.json({ok:true})}catch(e){res.status(500).json({ok:false})}});
app.post("/api/auth/register",async(req,res)=>{const {name,email,password}=req.body;if(!name||!email||!password)return res.status(400).json({error:"missing"});try{const count=await pool.query("select count(*)::int as count from users");if(count.rows[0].count>0)return res.status(403).json({error:"registration_disabled",message:"Le compte administrateur initial existe déjà. Utilisez une session administrateur pour créer les autres utilisateurs."});const bootstrapEmail=(process.env.BOOTSTRAP_ADMIN_EMAIL||"").trim().toLowerCase();if(bootstrapEmail && email.trim().toLowerCase()!==bootstrapEmail)return res.status(403).json({error:"bootstrap_email_required"});const hash=await bcrypt.hash(password,12);const r=await pool.query("insert into users(name,email,password_hash,role) values($1,$2,$3,'admin') returning id,name,email,role",[name,email.trim().toLowerCase(),hash]);const token=jwt.sign(r.rows[0],process.env.JWT_SECRET);res.json({token,user:r.rows[0]})}catch(e){res.status(409).json({error:"email_exists"})}});
app.post("/api/users",auth,async(req,res)=>{if(req.user.role!=="admin")return res.status(403).json({error:"admin_required"});const {name,email,password,role="user"}=req.body;if(!name||!email||!password)return res.status(400).json({error:"missing"});if(!["admin","user"].includes(role))return res.status(400).json({error:"invalid_role"});try{const hash=await bcrypt.hash(password,12);const r=await pool.query("insert into users(name,email,password_hash,role) values($1,$2,$3,$4) returning id,name,email,role",[name,email.trim().toLowerCase(),hash,role]);res.json(r.rows[0])}catch(e){res.status(409).json({error:"email_exists"})}});
app.get("/api/users",auth,async(req,res)=>{if(req.user.role!=="admin")return res.status(403).json({error:"admin_required"});const r=await pool.query("select id,name,email,role,created_at from users order by created_at");res.json(r.rows)});
app.post("/api/auth/login",async(req,res)=>{const r=await pool.query("select * from users where email=$1",[req.body.email]);if(!r.rows[0]||!(await bcrypt.compare(req.body.password,r.rows[0].password_hash)))return res.status(401).json({error:"invalid_credentials"});const {password_hash,...u}=r.rows[0];res.json({token:jwt.sign(u,process.env.JWT_SECRET),user:u})});
app.get("/api/structures",auth,async(req,res)=>{const r=await pool.query(`select s.*,coalesce(json_agg(distinct c) filter(where c.id is not null),'[]') contacts from structures s left join contacts c on c.structure_id=s.id group by s.id order by s.name`);res.json(r.rows)});
app.post("/api/structures",auth,async(req,res)=>{const x=req.body;const r=await pool.query(`insert into structures(name,type,street,postal_code,city,region,country,website,programming_url,programming_summary,programming_period,latitude,longitude,geom,status,notes) values($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,case when $12 is not null and $13 is not null then ST_SetSRID(ST_MakePoint($13,$12),4326)::geography end,$14,$15) returning *`,[x.name,x.type,x.street,x.postalCode,x.city,x.region,x.country,x.website,x.programmingUrl,x.programmingSummary,x.programmingPeriod,x.latitude,x.longitude,x.status,x.notes]);res.json(r.rows[0])});
app.get("/api/geo",auth,async(req,res)=>{const {lat,lon,radius=200}=req.query;const r=await pool.query(`select s.*,ST_Distance(s.geom,ST_SetSRID(ST_MakePoint($2,$1),4326)::geography)/1000 distance_km from structures s where s.geom is not null and ST_DWithin(s.geom,ST_SetSRID(ST_MakePoint($2,$1),4326)::geography,$3*1000) order by distance_km`,[lat,lon,radius]);res.json(r.rows)});
app.post("/api/import/excel",auth,upload.single("file"),async(req,res)=>{const wb=xlsx.readFile(req.file.path),sheet=wb.Sheets[wb.SheetNames[0]],rows=xlsx.utils.sheet_to_json(sheet,{defval:""});let count=0;for(const x of rows){await pool.query(`insert into structures(name,type,street,postal_code,city,region,country,website,programming_period,status) values($1,$2,$3,$4,$5,$6,$7,$8,$9,$10)`,[x.nom||x.name||"Sans nom",x.type,x.rue||x.street,x.CP||x.postal_code,x.ville||x.city,x.region,x.pays||x.country,x.site||x.website,x.programmation||x.programming_period,"À qualifier"]);count++}fs.unlinkSync(req.file.path);res.json({imported:count})});
app.get("/api/lists",auth,async(req,res)=>{const r=await pool.query(`select l.*,count(lm.contact_id)::int members from mailing_lists l left join list_members lm on lm.list_id=l.id group by l.id order by l.name`);res.json(r.rows)});
app.get("/api/lists/:id/members",auth,async(req,res)=>{const r=await pool.query(`select lm.*,c.name,c.role,c.email,c.phone,s.name structure_name from list_members lm join contacts c on c.id=lm.contact_id join structures s on s.id=c.structure_id where lm.list_id=$1 order by c.name`,[req.params.id]);res.json(r.rows)});
app.post("/api/lists/:id/send",auth,async(req,res)=>{const {contactIds,mailboxId,subject,body,attachments=[]}=req.body;let sent=0;for(const cid of contactIds||[]){const c=await pool.query("select c.*,s.id structure_id from contacts c join structures s on s.id=c.structure_id where c.id=$1",[cid]);if(c.rows[0]){await pool.query("insert into emails(user_id,mailbox_id,structure_id,contact_id,to_email,subject,body,attachments,status) values($1,$2,$3,$4,$5,$6,$7,$8,$9)",[req.user.id,mailboxId,c.rows[0].structure_id,cid,c.rows[0].email,subject,body,JSON.stringify(attachments),"queued"]);sent++}}res.json({queued:sent})});
app.get("/api/emails",auth,async(req,res)=>{const r=await pool.query(`select e.*,s.name structure_name from emails e left join structures s on s.id=e.structure_id where e.user_id=$1 order by e.created_at desc`,[req.user.id]);res.json(r.rows)});
app.post("/api/contacts",auth,async(req,res)=>{const x=req.body;const r=await pool.query("insert into contacts(structure_id,name,role,email,phone,notes) values($1,$2,$3,$4,$5,$6) returning *",[x.structureId,x.name,x.role,x.email,x.phone,x.notes]);res.json(r.rows[0])});
app.post("/api/mailboxes",auth,async(req,res)=>{const r=await pool.query("insert into mailboxes(user_id,email,provider) values($1,$2,$3) returning id,email,provider",[req.user.id,req.body.email,req.body.provider]);res.json(r.rows[0])});
app.get("/api/mailboxes",auth,async(req,res)=>{const r=await pool.query("select id,email,provider,created_at from mailboxes where user_id=$1",[req.user.id]);res.json(r.rows)});
app.get("/api/program-stats/:structureId",auth,async(req,res)=>{const r=await pool.query("select * from program_stats where structure_id=$1 order by updated_at desc",[req.params.structureId]);res.json(r.rows)});
async function bootstrapAdmin(){const email=(process.env.BOOTSTRAP_ADMIN_EMAIL||"").trim().toLowerCase();const password=process.env.BOOTSTRAP_ADMIN_PASSWORD||"";if(!email||!password)return;const r=await pool.query("select count(*)::int as count from users");if(r.rows[0].count===0){const hash=await bcrypt.hash(password,12);await pool.query("insert into users(name,email,password_hash,role) values($1,$2,$3,'admin')",[process.env.BOOTSTRAP_ADMIN_NAME||"Administrateur",email,hash]);console.log("Bootstrap admin created for "+email)}}
async function start(){await bootstrapAdmin();app.listen(process.env.PORT||3000,()=>console.log("Diffusion CRM on "+(process.env.PORT||3000)))}
start().catch(e=>{console.error(e);process.exit(1)});
